### ISSUE TITLE
Any plan to publish this package to pypi.org?

### ISSUE THREAD

**Issue by zhaofeng-shu33** [caponetto/bhc#1]
I am a researcher on related topic and I want to compare the results of different hierarchical clustering methods. Currently I find inconvenient to include the source code of Bayesian Rose Tree in my experiment code repos (https://github.com/zhaofeng-shu33/hierarchical_clustering_stability). It is better to write something like "bhc" in "requirements.txt" I think.

**Comment by caponetto** [comment]
Hi @zhaofeng-shu33, thanks for the interest.
Yes, the original plan is to publish the code on pypi.org. 
However, I'd like to have some unit tests and a blog post first. 
Eventually, I'll do that but it is not a short term thing.

**Comment by zhaofeng-shu33** [comment]
Thanks for your reply
